pipeline:
  build:
    image: amarburg/remote-compile:latest
    hosts: matlab.san.apl.washington.edu
    user: matlab
    target: tempdir
    exclude: .git/
    script:
      - make
      - ./main
    secrets: [ ssh_privkey ]

  test:
    image: alpine:latest
    commands:
      - ./main
