pipeline:
  build:
    image: ubuntu:latest
    commands:
      - apt-get update && apt-get install -y net-tools
      - /sbin/ifconfig

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
