pipeline:
  build:
    image: amarburg/remote-compile:latest
    hosts: matlab.san.apl.washington.edu
    user: matlab
    target: tempdir
    exclude: .git/
    script:
      - ls -al
      - touch foo
    secrets: [ ssh_privkey ]
